-- This migration was auto-generated by Prisma.
-- Manual SQL removed — run `bunx prisma migrate dev --name add_seat_system` to regenerate.
--
-- Changes:
--   Ticket: added flightId (NOT NULL, FK → Flight), made seatNumber nullable,
--           added seatSurcharge, added @@unique([flightId, seatNumber])

-- AlterTable: Add flightId to Ticket, make seatNumber nullable, add seatSurcharge
ALTER TABLE "Ticket" ADD COLUMN "flightId" TEXT;
ALTER TABLE "Ticket" ADD COLUMN "seatSurcharge" DECIMAL(10,2) NOT NULL DEFAULT 0;

-- Backfill flightId from Booking
UPDATE "Ticket" t
SET "flightId" = b."flightId"
FROM "Booking" b
WHERE t."bookingId" = b."id";

-- Now make flightId NOT NULL
ALTER TABLE "Ticket" ALTER COLUMN "flightId" SET NOT NULL;

-- Make seatNumber nullable
ALTER TABLE "Ticket" ALTER COLUMN "seatNumber" DROP NOT NULL;

-- Add foreign key for flightId
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_flightId_fkey"
  FOREIGN KEY ("flightId") REFERENCES "Flight"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Add unique constraint on (flightId, seatNumber) to prevent double-booking
CREATE UNIQUE INDEX "Ticket_flightId_seatNumber_key" ON "Ticket"("flightId", "seatNumber");

-- Add index on flightId
CREATE INDEX "Ticket_flightId_idx" ON "Ticket"("flightId");
